services:
  - type: web
    name: helpdesk-agent
    env: python
    plan: free
    buildCommand: pip cache purge && pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.13

